n0-computer/iroh-gossip

- Cargo.lock
- Cargo.toml
- deny.toml
- src/net.rs
Now that `iroh-router` exists, we can move this into the actual crate.
> refactor: add `ProtocolHandler` implementation

- Cargo.lock
- Cargo.toml
- deny.toml
- src/rpc.rs
- src/rpc/client.rs
Use quic-rpc v0.15.0 and adapt API. Most notably we can get rid of an entire type parameter.
Gossip::handle_rpc_request type parameters adapted to v0.15
rpc::client::Client type parameters adapted to v0.15
rpc::client::Client::new adapted to v0.15
> refactor!: use quic-rpc 0.15

- Cargo.lock
- Cargo.toml
- deny.toml
- src/net.rs
- src/rpc.rs
- src/rpc/client.rs
...lazily created so it doesn't cost much if you don't use it
- handle_rpc_request takes self, not &self
~~The RpcHandler stuff should be in quic-rpc maybe, or at least somehow DRYed.~~
> feat: Add in-memory rpc client and handler

- Cargo.lock
- Cargo.toml
- src/cli.rs
- src/lib.rs
Add gossip cli from iroh
None, this just adds stuff under the "cli" feature flag that is off by default.
Note: the API under the "cli" feature flag is tested, but it wasn't tested in iroh either. Given that it is a non-default flag I think we can still merge it. The alternative is throwing away all cli stuff entirey.
> feat: add cli

- examples/chat.rs
- src/net.rs
- src/proto.rs
Simplifies the construction of a new `iroh::net::Gossip` handler.
- removed `iroh::net::Gossip::from_endpoint` 
- added `iroh::net::Gossip::builder`
- added `iroh::net::Builder`
> feat!: introduce builder pattern to construct Gossip

- examples/chat.rs
- src/net.rs
- src/rpc.rs
- make the `join` explicit 
- align API naming between RPC and direct calls
- rename `net::Gossip::join` -> `net::Gossip::subscribe_and_join`
- added `net::Gossip::subscribe`
- rename `net::Gossip::join_with_opts` -> `net::Gossip::subscribe_with_opts` 
- rename `net::Gossip::join_with_stream` -> `net::Gossip::subscribe_with_stream`
> refactor!: align api naming between RPC and direct calls

- src/net.rs
`iroh::dialer` is going away, this removes the usage
> refactor: manually track dials, instead of using `iroh::dialer`

- src/net.rs
Progress towards better connection handling. Until #13 subscriptions were kept around for the duration of the run even when no longer needed. As a consequence, a notable chunk of code never ran that affects ending and accepting connections, with quick re-connection being a pain point. This PR tries to improve connection handling, but I don't think this is the end of the issues.
Changes are:
- we keep around the sender for the alternative connection. The alternative connection is that one with a different origin (whether we are or not the dialer). This seems to be original intent of keeping both connections, but dropping the sender to the alternative one effectively ends it because the connection loops has no longer a channel to read messages from for sending. This is bad because the that …
> fix: improve connection handling

- src/net.rs
- src/rpc.rs
There was a task leak because the lazily created rpc handler task was capturing an arced copy of the AbortOnDropHandle that keeps the task alive, so this task would never die. Also, this would keep alive the Gossip object forever *if* the lazy gossip task is started.
In this PR we introduce an Inner and make sure that the rpc handler only needs Inner, not full Gossip. That way we avoid the circular reference.
As a side benefit, we replace 2 arcs inside the Gossip with 1 arc for the Inner.
None
> fix: prevent task leak for rpc handler task

- src/net.rs
v0.30.0 introduced a regression: the Rx side of a gossip subscription was no longer `Sync`. I believe this was simply do to a missed `+ Sync` bound.
I reintroduce that `+ Sync` bound, and my code from 0.29 starts compiling again.
There's a PR open to fix this with a larger refactor, but I simply need the regression fixed :)
Feel free to close this PR if you'd rather just finish the refactor.
> add Sync bound to EventStream's inner

- Cargo.lock
- Cargo.toml
- src/lib.rs
- src/net.rs
- src/net/handles.rs
- src/net/util.rs
- src/proto/util.rs
- src/rpc.rs
Uses explict error types, instead of `anyhow`.
Ref https://github.com/n0-computer/iroh/issues/2741
Returned errors are now `iroh::net::Error` instead of `anyhow::Error` for all net interfaces.
> feat!: use explicit errors

- Cargo.lock
- Cargo.toml
- src/net.rs
- src/proto.rs
Release prep! Update `iroh`, `quic-rpc`, and `quic-rpc-derive`.
Removes `iroh-test` dependency in favor of `tracing-test`.
> chore: update dependencies

- .github/workflows/ci.yaml
- Cargo.lock
- Cargo.toml
- deny.toml
- examples/chat.rs
- src/net.rs
- src/net/handles.rs
- src/net/util.rs
- src/proto.rs
- src/proto/hyparview.rs
- src/proto/plumtree.rs
- src/proto/state.rs
- src/proto/tests.rs
- src/proto/topic.rs
- src/proto/util.rs
This updates `iroh-gossip` to make it compile to `wasm32-unknown-unknown` and run in browsers.
* Change Cargo.toml to compile to `cdylib` in addition to `rlib`
* Use `n0-future` for spawning tasks, time, and async utils
* Disable unneeded features of a few crates
* Do not wait for direct addresses to arrive, because that doesn't ever resolve in browsers - instead we wait for either the home relay or the direct addresses to be ready before launching gossip
> feat: compile to wasm and run in browsers

- Cargo.lock
- Cargo.toml
- deny.toml
Upgrade to `iroh@v0.33`, `quic-rpc@v0.18.2`, and `quic-rpc-derive@v0.18.2`.
> chore: upgrade to latest `iroh` and `quic-rpc`

- Cargo.lock
- Cargo.toml
- deny.toml
This PR updates the following dependencies to use their main branches:
- `iroh` from `https://github.com/n0-computer/iroh.git`
- `quic-rpc` from `https://github.com/n0-computer/quic-rpc.git`
> chore: patch to use main branch of iroh dependencies

- src/net.rs
- src/proto/hyparview.rs
- src/proto/state.rs
This should fix #10. It has two changes:
* On `main`, new incoming connections are rejected unless an old incoming connection timed out or are closed properly. This logic was most recently adapted in #22. The current situation is not ideal, because it means that if a peer reconnects without closing the previous connection properly, the new connection will be rejected. This PR changes the logic so that *all* incoming connections are accepted, and we *always* use the newest connection for sending messages. When a new connection is accepted, old connections are not aborted immediately. Instead we close our send stream on the old connection, which makes the peer close its receive stream. If the peer also uses the new connection only, the connection will close on our side as well. This means …
> fix: allow instant reconnects, and always prefer newest connection

- Cargo.lock
- Cargo.toml
- src/metrics.rs
- src/net.rs
Updates #58  for the latest iroh-metrics PR (see link below).
Depends on #58
Depends on  https://github.com/n0-computer/iroh/pull/3278 and 
Depends on https://github.com/n0-computer/iroh-metrics/pull/22
Depends on https://github.com/n0-computer/iroh-metrics/pull/23
> refactor: Update metrics to latest iroh-metrics PR

- .cargo/config.toml
- .github/workflows/ci.yaml
- Cargo.lock
- Cargo.toml
- deny.toml
- src/metrics.rs
- src/net.rs
- src/proto/state.rs
- src/proto/tests.rs
Adapts iroh-metrics for https://github.com/n0-computer/iroh-metrics/pull/15 and https://github.com/n0-computer/iroh/pull/3262
Depends on https://github.com/n0-computer/iroh/pull/3262
* `metrics::Metrics` now implements `MetricsGroup` from the  ìroh-metrics@0.34`
* Metrics are no longer tracked into the `static_core` from `iroh-metrics`, but instead are tracked per `Gossip` and exposed via `Gossip::metrics`
* `proto::state::State::handle` now takes `Option<&Metrics>` as new 4th parameter
> refactor!: use new iroh-metrics version, no more global tracking

- Cargo.lock
- Cargo.toml
- README.md
- deny.toml
- examples/chat.rs
- examples/setup.rs
- src/net.rs
Update to the latest `iroh`, `quic-rpc`, and `quic-rpc-derive` release.
> chore: update to `iroh` v0.35

- src/proto.rs
- src/proto/plumtree.rs
- src/proto/state.rs
- src/proto/topic.rs
Previously, on large swarms with many messages published the batched list of `IHave` lazy pushes sent to a peer could become larger than the configured max_message_size. If that happened, things would break in the send loop in the `net` module, because that is where the max_message_size is checked.
Fixing this is complicated by the fact that the `proto` module is, so far, encoding-agnostic. The solution implemented here is maybe not the cleanest, but it works: We assume `postcard` encoding for calculating how many `IHave`s we can fit into a message. I did not yet come up with a clean and not too complex solution for handling this differently, also I don't see a reason for not encoding in postcard. We might want to document this constraint though, should anyone use the `proto`  module on …
> fix: respect max message size when constructing IHave messages

- src/net.rs
- src/proto/hyparview.rs
- src/proto/plumtree.rs
- src/proto/topic.rs
- tests/sim.rs
This PR combines the "protocol improvements" PRs into one. See the individual commit messages for details.
Combined, these commits improve the reliability and behavior of the swarm layer (hyparview) significantly.
**refactor(hyparview): Improve disconnect handling**
5156d00f72be478872e7cecdf1b95d739b3b4fca
This improves the abstractions around when Disconnect messages are sent
and when peers are disconnected. Through a new RemovalReason enum, we
can handle this much cleaner. We also store in the local state if we
intended to disconnect from a peer, to not remove that peer from our
passive view once the peer is actually disconnected on the network layer.
**fix(hyparview)!: Only add peers to active view after receiving neighbor messages (#56)**
5a441e6cf5589fc3c7cf3c290005b1094895038c
This …
> feat/fix: Protocol improvements and fixes

- examples/chat.rs
- src/api.rs
- src/lib.rs
- src/net.rs
Cleanup of module structure on top of #67 
This is in a separate PR to make reviewing of #67 easier.
* Renamed `iroh_gossip::net::handles` to `iroh_gossip::api`
* The following reexports from `iroh_gossip::net` are removed. Import them from `iroh_gossip::api` instead. `{Command, Event, GossipApi, GossipEvent, GossipReceiver, GossipSender};`
* The `iroh_gossip::api` module now is available if either the `net` or the `rpc` features are enabled
> refactor!: improve module structure

- Cargo.lock
- Cargo.toml
- deny.toml
This PR updates the following dependencies to use their main branches:
- `iroh` from `https://github.com/n0-computer/iroh.git`
- `irpc` from `https://github.com/n0-computer/irpc.git`
- `iroh-base` from `https://github.com/n0-computer/iroh.git`
> chore: add patch for `iroh` dependencies

- README.md
> docs: Replace `iroh-net` mention in README

- Cargo.lock
- Cargo.toml
- src/net.rs
In prep for the `iroh-gossip` 0.92 release, this upgrades `iroh`, `iror-base`, `irpc`, `tracing-subscriber` and `n0-snafu`
> chore: upgrade `iroh`, `iroh-base`, `irpc`

- src/net.rs
Allow to customize the ALPN for outgoing gossip connections.
Also updates cargo deps (had cargo-deny warnings otherwise).
> feat: set custom ALPN

- src/net/util.rs
While doing some memory profiling on iroh-gossip I found an allocation that is not needed. It can get quite hot, so good to save this.
> perf: don't allocate in `Timers::wait_next`
